apiVersion: v1
data:
  prometheus-additional.yaml: LSBqb2JfbmFtZTogIms4c3BhY2tldC1tZXRyaWNzIgogIG1ldHJpY3NfcGF0aDogL21ldHJpY3MKICBzY3JhcGVfaW50ZXJ2YWw6IDI1cwogIHN0YXRpY19jb25maWdzOgogIC0gdGFyZ2V0czogW2s4c3BhY2tldC5rOHNwYWNrZXQuc3ZjLmNsdXN0ZXIubG9jYWw6ODA4MF0K
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
