---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: node-problem-detector
  namespace: flux-system
spec:
  interval: 5m0s
  timeout: 1m0s
  url: https://charts.deliveryhero.io/

