---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: npd
  namespace: flux-system
spec:
  chart:
    spec:
      chart: node-problem-detector
      sourceRef:
        kind: HelmRepository
        name: node-problem-detector
      version: 2.3.14
  interval: 1m0s
  targetNamespace: node-problem-detector
  releaseName: node-problem-detector
  install:
    remediation:
      retries: 7
    createNamespace: true
  upgrade:
    remediation:
      retries: 7
  valuesFrom:
  - kind: ConfigMap
    name: npd-values

