apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helm-npd-release.yaml       
- helm-npd-repo.yaml
configMapGenerator:
- name: npd-values
  namespace: flux-system
  files:
  - values.yaml
configurations:
- kustomizeconfig.yaml

