apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: contour-selfsigned  
spec:
  secretName: contour-selfsigned 
  duration: 2160h # 90 days
  renewBefore: 4h
  commonName: selfsigned.innascor-k8s.de
  issuerRef:
    name: selfsigned

