apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: nginx-values
  namespace: flux-system
  files:
  - values.yaml
resources:
- helm-ingress-nginx-repo.yaml
- helm-ingress-nginx-release.yaml
