apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: nginx-values
  namespace: flux-system
  files:
  - values.yaml=values.yaml
  #- values.yaml=values.yaml-ds
configurations:
- kustomizeconfig.yaml
resources:
- helm-ingress-nginx-repo.yaml
- helm-ingress-nginx-release.yaml
