apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nginx-ingress2
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
    - ingress
  selector:
    matchExpressions:
      - key: "app.kubernetes.io"
        operator: In
        values:
          - ingress-nginx
  podMetricsEndpoints:
    - port: metrics
