apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  #generatorOptions:
  #  disableNameSuffixHash: true
  #configMapGenerator:
  #- name: prometheus-values
  #  namespace: flux-system
  #  files:
  #  - values.yaml
resources:
- prometheus-release.yaml  
- prometheus.repo.yaml
