---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus
      version: "66.3.0"
  dependsOn:
  - name: helm-ingress
  interval: 1m0s
  targetNamespace: monitoring
  releaseName: prometheus
  install:
    remediation:
      retries: 7
    createNamespace: true
  upgrade:
    remediation:
      retries: 7
  valuesFrom:
  - kind: ConfigMap
    name: prometheus-values
