grafana:
  enabled: true
  ingress:
    enabled: true
    hosts:
    - grafana.${clustername}.zwerk.org

prometheus:
  enabled: true
  ingress:
    enabled: true
    hosts:
    - prometheus.${clustername}.zwerk.org
