apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minio-operator
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: minio-operator
  path: ./              
  prune: true
  wait: true           
  timeout: 5m0s
  # optional: apply in a target namespace (only for namespace-scoped objects)
  # targetNamespace: minio-operator

