apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
  namespace: projectcontour
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: contour-selfsigned  
  namespace: projectcontour
spec:
  secretName: contour-selfsigned 
  duration: 2160h # 90 days
  renewBefore: 4h
  commonName: selfsigned.zwerk.org
  issuerRef:
    name: selfsigned

