apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: contour-values
  namespace: flux-system
  files:
  - values.yaml
configurations:
- kustomizeconfig.yaml
resources:
- contour-release.yaml
- contour-repo.yaml
