apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#configMapGenerator:
#  - name: contour-values
#    files:
#      - values.yaml
#configurations:
#  - kustomizeconfig.yaml
resources:
  - contour.yaml
#  - contour-release.yaml
#  - contour-repo.yaml
  - gatewayclass.yaml
  - ingressclass.yaml
