---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: flux-system
spec:
  chart:
    spec:
      chart: alloy
      sourceRef:
        kind: HelmRepository
        name: alloy
      version: "1.2.1"
  dependsOn:
    - name: prometheus
  interval: 1m0s
  targetNamespace: alloy
  releaseName: alloy
  install:
    remediation:
      retries: 7
    createNamespace: true
  upgrade:
    remediation:
      retries: 7
  valuesFrom:
    - kind: ConfigMap
      name: values
