---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kyverno
      sourceRef:
        kind: HelmRepository
        name: kyverno
      version: v3.3.7
  interval: 1m0s
  targetNamespace: kyverno
  releaseName: kyverno
  install:
    remediation:
      retries: 7
    createNamespace: true
  upgrade:
    remediation:
      retries: 7
  values:
    replicaCount: 3
