---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-upgrade-controller-plan
  namespace: flux-system
spec:
  dependsOn:
    - name: system-upgrade-controller
  decryption:
    provider: sops
  path: base/system-upgrade-controller/plan
  sourceRef:
    kind: GitRepository
    name: gitrepo
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: true
  interval: 1m
  prune: true
