apiVersion: v1
kind: Secret
metadata:
  name: capi-system
  namespace: system-upgrade
type: Opaque
stringData:
  upgrade.sh: |
    #!/bin/sh
    set -e
    sysctl fs.inotify.max_user_instances=8192 
    sysctl fs.inotify.max_user_watches=524288
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: capi-system2
  namespace: system-upgrade
  labels:
    os: upgrade
spec:
  concurrency: 1
#  nodeSelector:
#    matchExpressions:
#      - { key: beta.kubernetes.io/os, operator: In, values: ["true"]}
  serviceAccountName: system-upgrade
  secrets:
    - name: capi-system
      path: /host/run/system-upgrade/secrets/capi-system
  #drain:
  #  force: true
  version: bionic3
  upgrade:
    image: ubuntu
    command: ["chroot", "/host"]
    args: ["sh", "/run/system-upgrade/secrets/capi-system/upgrade.sh"]
