---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: promtail
  namespace: flux-system
spec:
  interval: 5m0s
  timeout: 1m0s
  url: https://grafana.github.io/helm-charts

