---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: promtail
  namespace: flux-system
spec:
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: promtail
      version: "6.16.6"
  dependsOn:
  - name: prometheus
  interval: 1m0s
  targetNamespace: promtail
  releaseName: promtail
  install:
    remediation:
      retries: 7
    createNamespace: true
  upgrade:
    remediation:
      retries: 7
  valuesFrom:
  - kind: ConfigMap
    name: values
