apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  #configMapGenerator:
  #- name: dashboard-values
  #  namespace: flux-system
  #  files:
  #  - values.yaml
  #configurations:
  #- kustomizeconfig.yaml
resources:
- metrics-release.yaml  
- metrics-repo.yaml
