---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metrics
  namespace: flux-system
spec:
  interval: 5m0s
  timeout: 1m0s
  url: https://kubernetes-sigs.github.io/metrics-server/

