apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: certmanager-values
  namespace: flux-system
  files:
  - values.yaml
resources:
- certmanager-release.yaml  
- certmanager-repo.yaml
