---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: alloy
  namespace: flux-system
spec:
  dependsOn:
    - name: prometheus
  decryption:
    provider: sops
  path: base/alloy
  sourceRef:
    kind: GitRepository
    name: gitrepo
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: true
  interval: 1m
  prune: true
