---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: contour-add
  namespace: flux-system
spec:
  dependsOn:
  - name: contour
  decryption:
    provider: sops
  path: base/contour-add
  sourceRef:
    kind: GitRepository
    name: gitrepo
  interval: 1m
  prune:    true
