---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crds
  namespace: flux-system
spec:
  decryption:
    provider: sops
  path: base/crds
  sourceRef:
    kind: GitRepository
    name: gitrepo
  interval: 1m
  prune:    true
