---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: keda-dummy
  namespace: flux-system
spec:
  dependsOn:
  - name: keda
  decryption:
    provider: sops
  path: base/keda-dummy
  sourceRef:
    kind: GitRepository
    name: gitrepo
  interval: 1m
  prune:    true
