---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: keda
  namespace: flux-system
spec:
  decryption:
    provider: sops
  path: base/keda
  sourceRef:
    kind: GitRepository
    name: gitrepo
  interval: 1m
  prune:    true
