---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prometheus-addons
  namespace: flux-system
spec:
  dependsOn:
  - name: prometheus
  path: base/prometheus-addons
  sourceRef:
    kind: GitRepository
    name: gitrepo
  interval: 1m
  prune:    true
