---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prometheus
  namespace: flux-system
spec:
  decryption:
    provider: sops
  path: base/prometheus
  sourceRef:
    kind: GitRepository
    name: gitrepo
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-vars
      optional: true
  interval: 1m
  prune:    true
