---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: security
  namespace: flux-system
spec:
  dependsOn:
  - name: keda-dummy
  decryption:
    provider: sops
  path: base/security
  sourceRef:
    kind: GitRepository
    name: gitrepo
  interval: 1m
  prune:    true
