---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno-reporter
  namespace: flux-system
spec:
  chart:
    spec:
      chart: policy-reporter
      version: 2.18.3
      sourceRef:
        kind: HelmRepository
        name: kyverno-policy-reporter
  dependsOn:
  - name: prometheus
  interval: 1m0s
  targetNamespace: kyverno-reporter
  releaseName: kyverno-reporter
  install:
    remediation:
      retries: 7
    createNamespace: true
  upgrade:
    remediation:
      retries: 7
  valuesFrom:
  - kind: ConfigMap
    name: kyverno-reporter-values
