apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: loki-values
  namespace: flux-system
  files:
  - values.yaml
configurations:
- kustomizeconfig.yaml
resources:
- loki-release.yaml  
- loki-repo.yaml
- grafana-datasource.yaml
