apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: loki-values
  namespace: flux-system
  files:
  - values.yaml
resources:
- loki-release.yaml  
- loki-repo.yaml
- grafana-datasource.yaml
