---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  chart:
    spec:
      chart: loki-distributed
      sourceRef:
        kind: HelmRepository
        name: loki
      version: "0.80.5"
  dependsOn:
  - name: prometheus
  interval: 1m0s
  targetNamespace: loki
  releaseName: loki
  install:
    remediation:
      retries: 7
    createNamespace: true
  upgrade:
    remediation:
      retries: 7
  valuesFrom:
  - kind: ConfigMap
    name: loki-values
