---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux
  namespace: flux-system
spec:
  chart:
    spec:
      chart: flux
      sourceRef:
        kind: HelmRepository
        name: flux
      version: "flux2-2.15.0"
  interval: 1m0s
  targetNamespace: flux-system
  releaseName: prometheus
  install:
    remediation:
      retries: 7
    createNamespace: true
  upgrade:
    remediation:
      retries: 7
