---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flux
  namespace: flux-system
spec:
  type: oci
  interval: 5m0s
  timeout: 1m0s
  url: oci://ghcr.io/fluxcd-community/charts/flux2

